### ISSUE TITLE
[Install] 

### ISSUE THREAD

**Issue by ErdosEuge** [streamlit/demo-self-driving#11]
Traceback (most recent call last):
  File "/Users/andreosee/anaconda3/bin/streamlit", line 6, in <module>
    from streamlit.cli import main
  File "/Users/andreosee/anaconda3/lib/python3.7/site-packages/streamlit/__init__.py", line 99, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "/Users/andreosee/anaconda3/lib/python3.7/site-packages/streamlit/delta_generator.py", line 25, in <module>
    from streamlit.proto import BlockPath_pb2
  File "/Users/andreosee/anaconda3/lib/python3.7/site-packages/streamlit/proto/BlockPath_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
(base) ➜  ~

**Comment by randyzwitch** [comment]
https://stackoverflow.com/a/61961016/2394542
