### ISSUE TITLE
Running streamlit run https://raw.githubusercontent.com/streamlit/demo-self-driving/master/app.py fails

### ISSUE THREAD

**Issue by Code4SAFrankie** [streamlit/demo-self-driving#3]
Running `streamlit run https://raw.githubusercontent.com/streamlit/demo-self-driving/master/app.py` gives me this error:

```
E:\WPy-3710\python-3.7.1.amd64>streamlit run https://raw.githubusercontent.com/streamlit/demo-self-driving/master/app.py
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\streamlit.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\streamlit\cli.py", line 149, in main_run
    _main_run(fp.name, args)
  File "c:\python27\lib\site-packages\streamlit\cli.py", line 179, in _main_run
    bootstrap.run(file, command_line, args)
  File "c:\python27\lib\site-packages\streamlit\bootstrap.py", line 181, in run
    server.add_preheated_report_session()
  File "c:\python27\lib\site-packages\streamlit\server\Server.py", line 393, in add_preheated_report_session
    session = self._add_browser_connection(PREHEATED_REPORT_SESSION)
  File "c:\python27\lib\site-packages\streamlit\server\Server.py", line 422, in _add_browser_connection
    command_line=self._command_line,
  File "c:\python27\lib\site-packages\streamlit\ReportSession.py", line 96, in __init__
    self._report, self._on_source_file_changed
  File "c:\python27\lib\site-packages\streamlit\watcher\LocalSourcesWatcher.py", line 87, in __init__
    module_name=None,  # Only the root script has None here.
  File "c:\python27\lib\site-packages\streamlit\watcher\LocalSourcesWatcher.py", line 110, in _register_watcher
    watcher=FileWatcher(filepath, self.on_file_changed), module_name=module_name
  File "c:\python27\lib\site-packages\streamlit\watcher\EventBasedFileWatcher.py", line 86, in __init__
    file_watcher.watch_file(file_path, on_file_changed)
  File "c:\python27\lib\site-packages\streamlit\watcher\EventBasedFileWatcher.py", line 160, in watch_file
    folder_handler.add_file_change_listener(file_path, callback)
  File "c:\python27\lib\site-packages\streamlit\watcher\EventBasedFileWatcher.py", line 248, in add_file_change_listener
    md5 = util.calc_md5_with_blocking_retries(file_path)
  File "c:\python27\lib\site-packages\streamlit\watcher\util.py", line 68, in calc_md5_with_blocking_retries
    raise e
IOError: [Errno 13] Permission denied: 'c:\\users\\user\\appdata\\local\\temp\\tmpi3xndk'
```

Debug info

    Streamlit version: 0.47.2
    Python version: 3.7.1
    Using Conda? PipEnv? PyEnv? Pex? pip on WinPython
    OS version: Windows 10 version 1903
    Browser version: Firefox 69.0

**Comment by firstredpepper** [comment]
Same issue for me - any suggestions?

**Comment by Code4SAFrankie** [comment]
This video might be helpful: https://www.youtube.com/watch?v=uoI57uMdDD4

**Comment by treuille** [comment]
Thanks @Code4SAFrankie ! That video is very enlightening. We'd been doing automated Streamlit testing on Linux and MacOS, but not Windows and it looks like that was a mistake. I'll talk to the team about extending our tests to Windows.

**Comment by treuille** [comment]
On that note, I'm closing this issue because it's [tracked here](https://github.com/streamlit/streamlit/issues/301).

@Code4SAFrankie and @firstredpepper : Please follow that issue for updates on this bug.
