### ISSUE TITLE
Expired SSL Certificate

### ISSUE THREAD

**Issue by HelioGuilherme66** [streamlit/demo-self-driving#31]
I was experimenting this project for the first time and got this error:
```
  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.2.201:8501

2022-06-11 02:58:54.238 Uncaught app exception
Traceback (most recent call last):
  File "C:\Python39\lib\urllib\request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Python39\lib\http\client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python39\lib\http\client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Python39\lib\http\client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python39\lib\http\client.py", line 1040, in _send_output
    self.send(msg)
  File "C:\Python39\lib\http\client.py", line 980, in send
    self.connect()
  File "C:\Python39\lib\http\client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Python39\lib\ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Python39\lib\ssl.py", line 1041, in _create
    self.do_handshake()
  File "C:\Python39\lib\ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\streamlit\scriptrunner\script_runner.py", line 554, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\Helio\AppData\Local\Temp\tmps_c7nr8c\streamlit_app.py", line 294, in <module>
    main()
  File "C:\Users\Helio\AppData\Local\Temp\tmps_c7nr8c\streamlit_app.py", line 32, in main
    download_file(filename)
  File "C:\Users\Helio\AppData\Local\Temp\tmps_c7nr8c\streamlit_app.py", line 62, in download_file
    with urllib.request.urlopen(EXTERNAL_DEPENDENCIES[file_path]["url"]) as response:
  File "C:\Python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python39\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "C:\Python39\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Python39\lib\urllib\request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Python39\lib\urllib\request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>

```
Windows 10 64bit, Python 3.9.13

The Side Bar to Run the project was not rendered.

![image](https://user-images.githubusercontent.com/2866630/173168566-e7cf5618-053c-4c03-9681-8e76abea9a99.png)

**Comment by randyzwitch** [comment]
Hi @HelioGuilherme66 - 

How did you start this app? Meaning, did you clone the repo or are you pointing directly at the file on GitHub?

Best,
Randy

**Comment by HelioGuilherme66** [comment]
I did installed, just like the README doc says:
```
pip install --upgrade streamlit opencv-python
streamlit run https://raw.githubusercontent.com/streamlit/demo-self-driving/master/streamlit_app.py
```

Here is today's execution without arguments:
```
C:\Projects>streamlit
C:\Python39\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Python39\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
C:\Python39\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
Usage: streamlit [OPTIONS] COMMAND [ARGS]...

  Try out a demo with:

      $ streamlit hello

  Or use the line below to run your own script:

      $ streamlit run your_script.py

Options:
  --log_level [error|warning|info|debug]
  --version                       Show the version and exit.
  --help                          Show this message and exit.

Commands:
  activate  Activate Streamlit by entering your email.
  cache     Manage the Streamlit cache.
  config    Manage Streamlit's config settings.
  docs      Show help in browser.
  hello     Runs the Hello World script.
  help      Print this help message.
  run       Run a Python script, piping stderr to Streamlit.
  version   Print Streamlit's version number.
```

**Comment by randyzwitch** [comment]
This works for me on macOS; your error message to me seems to indicate you might have a separate issue with your overall environment.

My suggestion would be to create a virtual environment to start fresh, then run the commands.
